language: java
jdk:
  - oraclejdk8
script:
  - cd l5.testframework
  - mvn package
  - java -jar target/l5.testframework-1.0-SNAPSHOT.jar
  - cd ../l3.containers
  - mvn package
  - cd ../l2.sizes
  - mvn package
  - java -XX:-UseTLAB -jar target/l2.sizes.jar
  - cd ../l1.maven
  - mvn package
  
  
